version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=mongodb://mongo:HYYFMn80_JTxTZFmRSx6Q@78.46.190.73:27017
      - SECRET_KEY=f0e13b769ee3add58687bea8d1b010f9932e649ff5033eee5b02188e2f8b4344
    volumes:
      - .:/app
